# Generated by Django 6.1 on 2026-09-15 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_image_public_id_user_profile_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverypartner',
            name='profile_image',
        ),
    ]
