# Generated by Django 6.1 on 2026-09-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_category_description_remove_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_public_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
