# Generated by Django 6.1 on 2026-09-22 15:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_deliverypartner_profile_image'),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food_cart', to='accounts.customer')),
            ],
            options={
                'db_table': 'food_carts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodCartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='food.foodcart')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='food.fooditem')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='food.fooditemvariant')),
            ],
            options={
                'db_table': 'food_cart_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodCartItemAddon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='food.fooditemaddon')),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='food.foodcartitem')),
            ],
            options={
                'db_table': 'food_cart_item_addons',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='foodcartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'variant'), name='unique_food_cart_variant'),
        ),
        migrations.AddConstraint(
            model_name='foodcartitemaddon',
            constraint=models.UniqueConstraint(fields=('cart_item', 'addon'), name='unique_food_cart_item_addon'),
        ),
    ]
