# Generated by Django 6.1 on 2026-09-11 19:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_profile_image_public_id_user_profile_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintingService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('PRINT', 'Print'), ('XEROX', 'Xerox'), ('SCAN', 'Scan'), ('OTHER', 'Other')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'printing_services',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('payment_method', models.CharField(default='COD', editable=False, max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], db_index=True, default='PENDING', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='printing_orders', to='accounts.customer')),
            ],
            options={
                'db_table': 'print_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.URLField(max_length=1000)),
                ('cloudinary_public_id', models.CharField(blank=True, max_length=500, null=True)),
                ('file_type', models.CharField(blank=True, max_length=100, null=True)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('page_count', models.PositiveIntegerField(default=1)),
                ('color_type', models.CharField(choices=[('BLACK_WHITE', 'Black & White'), ('COLOR', 'Color')], default='BLACK_WHITE', max_length=20)),
                ('paper_size', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('A5', 'A5')], default='A4', max_length=10)),
                ('print_side', models.CharField(choices=[('SINGLE', 'Single Side'), ('DOUBLE', 'Double Side')], default='SINGLE', max_length=10)),
                ('copies', models.PositiveIntegerField(default=1)),
                ('page_start', models.PositiveIntegerField(blank=True, null=True)),
                ('page_end', models.PositiveIntegerField(blank=True, null=True)),
                ('price_per_page', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='printing.printingservice')),
                ('print_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='printing.printorder')),
            ],
            options={
                'db_table': 'print_documents',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('color_type', models.CharField(choices=[('BLACK_WHITE', 'Black & White'), ('COLOR', 'Color')], default='BLACK_WHITE', max_length=20)),
                ('paper_size', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('A5', 'A5')], default='A4', max_length=10)),
                ('print_side', models.CharField(choices=[('SINGLE', 'Single Side'), ('DOUBLE', 'Double Side')], default='SINGLE', max_length=10)),
                ('price_per_page', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pricing', to='printing.printingservice')),
            ],
            options={
                'db_table': 'print_pricing',
                'ordering': ['service', 'paper_size', 'color_type', 'print_side'],
            },
        ),
        migrations.AddIndex(
            model_name='printorder',
            index=models.Index(fields=['customer', 'status'], name='po_customer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='printorder',
            index=models.Index(fields=['customer', 'created_at'], name='po_customer_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='printpricing',
            constraint=models.UniqueConstraint(fields=('service', 'color_type', 'paper_size', 'print_side'), name='unique_print_pricing_configuration'),
        ),
    ]
