# Generated by Django 6.1 on 2026-09-15 08:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('image_url', models.URLField(max_length=1000)),
                ('image_public_id', models.CharField(blank=True, max_length=500, null=True)),
                ('mobile_image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('mobile_image_public_id', models.CharField(blank=True, max_length=500, null=True)),
                ('section', models.CharField(choices=[('HOME', 'Home'), ('GROCERY', 'Grocery'), ('FOOD', 'Food'), ('PRINTING', 'Printing')], db_index=True, default='HOME', max_length=30)),
                ('navigation_type', models.CharField(choices=[('NONE', 'None'), ('CATEGORY', 'Category'), ('SUBCATEGORY', 'Subcategory'), ('PRODUCT', 'Product'), ('FOOD_CATEGORY', 'Food Category'), ('FOOD_ITEM', 'Food Item'), ('URL', 'External URL')], default='NONE', max_length=30)),
                ('navigation_id', models.UUIDField(blank=True, null=True)),
                ('navigation_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'banners',
                'ordering': ['display_order', '-created_at'],
                'indexes': [models.Index(fields=['section', 'is_active'], name='banner_section_active_idx'), models.Index(fields=['start_at', 'end_at'], name='banner_schedule_idx')],
            },
        ),
        migrations.CreateModel(
            name='BannerButton',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('navigation_type', models.CharField(choices=[('NONE', 'None'), ('CATEGORY', 'Category'), ('SUBCATEGORY', 'Subcategory'), ('PRODUCT', 'Product'), ('FOOD_CATEGORY', 'Food Category'), ('FOOD_ITEM', 'Food Item'), ('URL', 'External URL')], default='NONE', max_length=30)),
                ('navigation_id', models.UUIDField(blank=True, null=True)),
                ('navigation_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='banner.banner')),
            ],
            options={
                'db_table': 'banner_buttons',
                'ordering': ['display_order', 'created_at'],
                'indexes': [models.Index(fields=['banner', 'is_active'], name='banner_btn_active_idx')],
            },
        ),
    ]
