# Generated by Django 6.1 on 2026-09-07 11:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('purpose', models.CharField(choices=[('signup', 'Signup'), ('login', 'Login'), ('password_reset', 'Password Reset')], db_index=True, max_length=30)),
                ('otp_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'email_otps',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'purpose', 'is_used'], name='email_otp_lookup_idx')],
            },
        ),
    ]
